spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:database}:${DB_PORT:3306}/${DB_NAME:dev}?createDatabaseIfNotExist=true
    username: ${DB_USER:mysql}
    password: ${DB_PASSWORD:thisIsReallyStrongPassword123}
    driver-class-name: com.mysql.cj.jdbc.Driver
